services:
  server:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    environment:
      NODE_ENV: production
      db_path: /data
      auth_token: ${auth_token}
    volumes:
      - db_data:/data
    ports:
      - 3000:3000

  caddy:
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
    environment:
      NODE_ENV: production
      host_name: ${host_name}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - 80:80
      - 443:443

volumes:
  db_data:
  caddy_data:
  caddy_config:
