services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      db_path: /data
      auth_token: ${auth_token}
    volumes:
      - static:/srv
      - db_data:/data
    ports:
      - 3000:3000

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    environment:
      host_name: ${host_name}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - static:/srv
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - 80:80
      - 443:443

volumes:
  static:
  db_data:
  caddy_data:
  caddy_config:
